import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import path from "node:path";

const envAssignmentPattern =
  /^(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/;

function stripMatchingQuotes(value: string) {
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1);
  }

  return value;
}

export function parseLocalEnv(source: string) {
  const values: Record<string, string> = {};
  const lines = source.split(/\r?\n/);

  for (const [index, line] of lines.entries()) {
    const trimmedLine = line.trim();

    if (!trimmedLine || trimmedLine.startsWith("#")) {
      continue;
    }

    const match = envAssignmentPattern.exec(trimmedLine);

    if (!match) {
      throw new Error(
        `Invalid environment variable assignment on line ${index + 1}.`,
      );
    }

    const [, key, rawValue] = match;
    values[key] = stripMatchingQuotes(rawValue.trim());
  }

  return values;
}

export function loadLocalEnvFile(rootDir: string, fileName = ".env.local") {
  const filePath = path.join(rootDir, fileName);

  if (!existsSync(filePath)) {
    return {
      filePath,
      values: {},
    };
  }

  return {
    filePath,
    values: parseLocalEnv(readFileSync(filePath, "utf8")),
  };
}

function escapeEnvValue(value: string) {
  return JSON.stringify(value);
}

export function formatLocalEnv(values: Record<string, string>) {
  return Object.entries(values)
    .sort(([leftKey], [rightKey]) => leftKey.localeCompare(rightKey))
    .map(([key, value]) => `${key}=${escapeEnvValue(value)}`)
    .join("\n");
}

export function syncCloudflareDevVarsFiles(args: {
  fileName?: string;
  sourceFileLabel: string;
  targetDirs: string[];
  values: Record<string, string>;
}) {
  const fileName = args.fileName ?? ".dev.vars";
  const body = formatLocalEnv(args.values);

  for (const targetDir of args.targetDirs) {
    const targetPath = path.join(targetDir, fileName);

    if (!body) {
      if (existsSync(targetPath)) {
        unlinkSync(targetPath);
      }

      continue;
    }

    writeFileSync(
      targetPath,
      [
        `# Generated by scripts/dev.ts from ${args.sourceFileLabel}.`,
        "# Do not commit this file.",
        body,
        "",
      ].join("\n"),
      "utf8",
    );
  }
}
